---
title: "Section 1B Theorems (1.26 - 1.32)"
author: "Mason Robinson"
date: "2026-04-03"
output: pdf_document
---
## Section 1B
### Theorem 1.26 Unique Additive Identity
A vector space has a unique additive identity.
#### Proof
Suppose $0$ and $0'$ are both additive identities for some vector space $V$. Then,

$0' = 0' + 0$  {since $0$ is an additive identity}
$0' + 0 = 0 + 0'$  {from commutativity}
$0 + 0' = 0$ {since 0' is an additive identity}

Thus, $0' = 0$, revealing $V$ has only one additive identity. $\blacksquare$

### Theorem 1.27 Unique Additive Inverse
Every element in a vector space has a unique additive inverse.

#### Proof
Suppose $V$ is a vector space. Let $v \in V$. Suppose $w$ and $w'$ are additive inverses of $v$ and $w, w' \in V$, but $w \not= w'.$ Then,

$w = w + 0 = w + (v + w')$ {Since $w'$ is an additive inverse of $v$, stated above}
$w + (v + w') = (w + v) + w'$ {From associativity}
$(w + v) + w' = 0 + w'$ {Since $w$ is an additive inverse of $v$, stated above}
$0 + w' = w'$ {from additive identity}
Since we have a contradiction since we previously stated that $w \not = w'$, this shows us that every $v \in V$ has a unique additive inverse. $\blacksquare$

### Theorem 1.30 The Number $0$ Times a Vector

$0 v = 0$ for every $v \in V.$

#### Proof
For $v \in V$, we have 
$0 v = (0 + 0)v$
$(0 + 0)v = 0v + 0v$ {From distributive property}
$0v + 0v = 0 + 0$
$0 + 0 = 0$

Thus, $0v = 0$. $\blacksquare$

### Theorem 1.31 A Number Times the Vector $0$
$a0 = 0$ for every $a \in \mathbb{F}$.

#### Proof
For $a \in \mathbb{F}$, we have
$a0 = a(0 + 0 + ... + 0)$
$a(0 + 0 + ... + 0) = (a0, a0, ..., a0)$ {From distribution property}
$(a0, a0, ..., a0) = (0, 0, ..., 0)$ {From multiplying a scalar by $0$}
$(0, 0, ..., 0) = 0$ {From definition 1.15 Notation: $0$}

Thus, $a0 = 0$ for every $a \in \mathbb{F}$. $\blacksquare$

### Theorem 1.32 The Number $-1$ Times a Vector
$(-1)v = -v$ for every $v \in V$.

#### Proof
For every $v \in V,$ we have

$v + (-1)v = 1(v) + -1(v)$ {From multiplicative identity of a vector space}
$1(v) + -1(v) = (1 + (-1))v$ {From distributive property}
$(1 + (-1))v = (0)v$
$(0)v = 0$ {From Theorem 1.30}

Thus, $(-1)v = -v$ for every $v \in V$. $\blacksquare$ 

