---
title: "Section 1B Definitions (1.19 - 1.29)"
author: "Mason Robinson"
date: "2026-04-03"
output: pdf_document
---

### 1.19 Addition, Scalar Multiplication
An *addition* on a set $V$ is a function that assigns an element $u + v \in V$ to each pair of elements $u, v \in V.$

A *scalar multiplication* on a set $V$ is a function that assigns an element $\lambda u \in V$ to each $\lambda \in \mathbb{F}$ and each $u \in V$.

### 1.20 Vector Space
A *vector space* is a set $V$ along with an addition on $V$ and a scalar multiplication on $V$ such that the following properties hold:

**Commutativity**
$u + v = v + u$ for all $u, v \in V$.

**Associativity**
$(u + v) + w = u + (v + w)$ and $(ab)v = a(bv)$ for all $u, v, w \in V$ and for all $a, b \in \mathbb{F}$.

**Additive Identity**
There exists an element $0 \in V$ such that $v + 0 = v$ for all $v \in V$.

**Multiplicative Identity**
$1v = v$ for all $v \in V$.

**Distributive Identity**
$a(u + v) = au + av$ and $(a + b)v = av + bv$ for all $a, b \in \mathbb{F}$ and all $u, v \in V$.

### 1.21 Vector, Point
Elements of a vector space are called *vectors* or *points*.

### 1.22 Real Vector Space, Complex Vector Space
A vector space over $\mathbb{R}$ is called a *real vector space*.

A vector space over $\mathbb{C}$ is called a *complex vector space*.

### 1.24 Notation: $\mathbb{F}^n$
If $S$ is a set, then $\mathbb{F}^S$ denotes the set of functions from $S$ to $\mathbb{F}$.

For $f, g \in \mathbb{F}^S$, the *sum* $f + g \in \mathbb{F}^S$ is the function defined by

$(f + g)(x) = f(x) + g(x)$ for all $x \in S$.

For $\lambda \in \mathbb{F}$ and $f \in \mathbb{F}^S$ is the function defined by

$(\lambda f)(x) = \lambda f(x)$ for all $x \in S$.

### 1.28 Notation: $-v, w - v$
Let $v, w \in V$. Then

$-v$ denotes the additive inverse of $v$.
$w - v$ is defined by $w + (-v)$.

### 1.29 Notation: $V$
$V$ denotes a vector space over $\mathbb{F}$.